name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
       - name: Deploy
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          HOST_NAME: 3.133.59.95
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${HOST_NAME} '
            cd /app &&
            git fetch origin main &&
            git checkout main &&
            git reset --hard origin/main &&
            sudo docker-compose down &&
            sudo docker-compose up -d
          '
